### PR TITLE
fix for 2024.5.0

### PR DESCRIPTION
**Pull request by Winor**
A quick fix for 2024.5.0 update.

### CODE REVIEW

**Comment by lloydbayley** [comment]
So glad someone is keeping up with this. I enjoy my animated backgrounds! :)
Unfortunately, I made the mods and it still won't show. How would I best debug this?

**Comment by Winor** [comment]
Absolutely. I use it on my TV Kiosk and I can't live without it!.
Have you tried to clear browser cache?
Umm not sure on how to debug it but If you open the HA dashboard with a lovelace-animated-background, press F12 and in console what is the output of: 
``` js
let Root = "";
Root = document.querySelector("home-assistant");
Root = Root && Root.shadowRoot;
Root = Root && Root.querySelector("home-assistant-main");
Root = Root && Root.shadowRoot;
Root = Root && Root.querySelector("ha-drawer partial-panel-resolver");
Root = (Root && Root.shadowRoot) || Root;
Root = Root && Root.querySelector("ha-panel-lovelace");
Root = Root && Root.shadowRoot;
Root = Root && Root.querySelector("hui-root");
Root.shadowRoot.getElementById("view").id;
```
it should output "view" meaming the code can find the element that require a change. I did not get too deep in understanding the code yet so the changes I made might only work for my usecase. let me know !

**Comment by lloydbayley** [comment]
Hmm..Still no go. Let me take it completely out and put it back in again. Just to be on the safe side.
More soon...

**Comment by lloydbayley** [comment]
Struggling here. It's being difficult. (As everything about debugging is!) - I'll have a go at it tomorrow. It's 8:20pm here and not much sleep was had last night, so I'm a bit dopey! Will report in then! :) Thanks!

**Comment by lloydbayley** [comment]
Well, I'm sorry to say that I can't make it work. I've tried every bloody trick in the book but it just won't show up at all.
For now, I've rolled back to the prev version but have a new install I did on a Rpi to play around with. I appreciate your efforts but java seems to have outsmarted me.....for now... :)

**Comment by Winor** [comment]
Worry not, when I get the time I will take a better look :)

**Comment by lloydbayley** [comment]
Cheers! Java is not my forté by ANY means. Python, ok, php ok, bash fine but not js

**Comment by Winor** [comment]
I just noticed other fork had fixed the issue, so I'm letting you know @lloydbayley https://github.com/rbogdanov/lovelace-animated-background

**Comment by lloydbayley** [comment]
G'day! I hadn't been back to this yet today but yes, it VERKS!!!!! :) Well done. I'm going to keep an eye on both forks.
Thanks again!

**Pull request closed without merging**
